FROM python:3.10.10
#This is sample docker image
# Copy app folder which contains logic to serve predictions
COPY ./app /app

WORKDIR /app

# Install the requirements
RUN pip install -r requirements.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]
EXPOSE 8080